version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: unisuam-api-php
        image: unisuam-api/php
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        extra_hosts:
            - "internal.host:host-gateway"
        networks:
            - unisuam-api-net
        depends_on:
            - db

    nginx:
        container_name: unisuam-api-nginx
        image: nginx:stable-alpine
        restart: unless-stopped
        build: ./docker/nginx
        tty: true
        ports:
            - "8000:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - unisuam-api-net
        depends_on:
            - app

    db:
        container_name: unisuam-api-db
        image: postgres:16.2
        restart: unless-stopped
        tty: true
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            PGDATA: ./docker/pgdata
            TZ: America/Sao_Paulo
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d ${DB_DATABASE} -U ${DB_USERNAME}" ]
            interval: 5s
            timeout: 5s
            retries: 5
        volumes:
            - ./docker/pgdata:/var/lib/postgresql/data
            - ./docker/pgdata/docker-entrypoint-initdb.sh:/docker-entrypoint-initdb.sh
        ports:
            - "5432:5432"
        networks:
            - unisuam-api-net

networks:
    unisuam-api-net:
        driver: bridge
